version: '3.8'
services:
  movies:
    image: hari1930/movie:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: hari1930/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: hari1930/recharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: hari1930/dth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
